name: Build and Push to Image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  PROJECT_ID: livrovivo
  REGION: us-central1-docker.pkg.dev
  REPOSITORY_PATH: livrovivo/container-images
  IMAGE_NAME: livebook-with-storage

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
          
      - uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'gh-actions-account@livrovivo.iam.gserviceaccount.com' 
          workload_identity_provider: 'projects/901339380733/locations/global/workloadIdentityPools/github/providers/my-repo'
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }} --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.REGION }}/${{ env.REPOSITORY_PATH }}/${{ env.IMAGE_NAME }}
        working-directory: src
 
      - name: Push image
        run: docker push ${{ env.REGION }}/${{ env.REPOSITORY_PATH }}/${{ env.IMAGE_NAME }}
