name: Build and Push to Image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  PROJECT_ID: livrovivo
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/livrovivo/cloud-run-source-deploy/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: cd src && docker build . --file Dockfile --tag ${{ env.GAR_LOCATION }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
